name: Shopping Cart CI

# Triggers the workflow on push but only for the main branch
on:
    push:
        branches: 
            - main

 # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
  
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 16
                cache: 'npm'
                cache-dependency-path: ./package-lock.json

            - name: Install dependencies
              run: npm install
            
            - name: Start React Application
              run: npm start

            - name: Perform Smoke Test
              run: npm test
               